# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Chipmunk' do
  
end

target 'CHCommon' do
    pod 'google-cast-sdk'
end

target 'CHDatabase' do
  pod "RealmSwift"
end

target 'CHHTTPServer' do
  pod "GCDWebServer"
  pod "RealmSwift"
  pod "SwiftyJSON"
end
