# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Chipmunk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for StreamIt
end

target 'CHDatabase' do
  pod "RealmSwift"
end

target 'CHHTTPServer' do
  pod "GCDWebServer", "~> 3.0"
end
